#!/bin/bash
pip install 'rosspy>=0.1.6'
wget https://water.usgs.gov/water-resources/software/PHREEQC/iphreeqc-3.7.3-15968.tar.gz
tar -xzvf iphreeqc-3.7.3-15968.tar.gz
pwd
cd iphreeqc-3.7.3-15968
./configure  --prefix=/home/runner/iphreeqc
make
make check
make install
pip show phreeqpy
pwd
cp /home/jovyan/iphreeqc-3.7.3-15968/src/.libs/libiphreeqc.so /srv/conda/envs/notebook/lib/python3.10/site-packages/phreeqpy/iphreeqc/libiphreeqc.so.0.0.0
